LAU-753 Idam User Disposer Summary
hmcts/disposer-idam-user pull request #134
Opened 2023-10-10 13:47 UTC by priyankaVerma21

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/LAU-753

### Change description ###
This change is summarise disposer run

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-10-10 13:57 UTC, MartinYSpasov requested changes

2023-10-10 17:02 UTC, priyankaVerma21 commented on src/main/java/uk/gov/hmcts/reform/idam/util/LoggingSummaryUtils.java
> +public final class LoggingSummaryUtils {
Test has been added

2023-10-10 17:02 UTC, priyankaVerma21 commented on src/main/java/uk/gov/hmcts/reform/idam/service/IdamUserDisposerService.java
> +        LoggingSummaryUtils.logSummary(disposerStartTime,disposerEndTime,allProcessedStaleUserIds.size(),
Verification of this method call has been added

2023-10-11 11:17 UTC, MartinYSpasov requested changes

2023-10-12 15:53 UTC, MartinYSpasov approved these changes

2023-10-16 09:33 UTC, merged